/* Generated by Quarry (C backend). */
#include "hil/telemetry.generated.h"

#include <string.h>

void hil_telemetry_SensorSample_init(hil_telemetry_SensorSample_t* record) {
    memset(record, 0, sizeof(*record));
}

size_t hil_telemetry_SensorSample_encoded_size(const hil_telemetry_SensorSample_t* record) {
    quarry_c_field_t fields[9];
    size_t field_count = 0U;
    uint8_t sequence_bytes[4];
    uint8_t timestamp_ms_bytes[8];
    uint8_t temperature_c_bytes[4];
    uint8_t battery_mv_bytes[2];
    uint8_t calibrated_bytes[1];
    uint8_t status_bytes[1];
    uint8_t readings_bytes[13];
    if (record->has_sequence) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, sequence_bytes, sizeof(sequence_bytes));
        (void)quarry_c_write_u32(&writer, record->sequence);
        fields[field_count].field_index = 0U;
        fields[field_count].bytes = sequence_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_timestamp_ms) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, timestamp_ms_bytes, sizeof(timestamp_ms_bytes));
        (void)quarry_c_write_u64(&writer, record->timestamp_ms);
        fields[field_count].field_index = 1U;
        fields[field_count].bytes = timestamp_ms_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_temperature_c) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, temperature_c_bytes, sizeof(temperature_c_bytes));
        (void)quarry_c_write_f32(&writer, record->temperature_c);
        fields[field_count].field_index = 2U;
        fields[field_count].bytes = temperature_c_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_battery_mv) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, battery_mv_bytes, sizeof(battery_mv_bytes));
        (void)quarry_c_write_u16(&writer, record->battery_mv);
        fields[field_count].field_index = 3U;
        fields[field_count].bytes = battery_mv_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_calibrated) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, calibrated_bytes, sizeof(calibrated_bytes));
        (void)quarry_c_write_bool(&writer, record->calibrated);
        fields[field_count].field_index = 4U;
        fields[field_count].bytes = calibrated_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_status) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, status_bytes, sizeof(status_bytes));
        (void)quarry_c_write_u8(&writer, (uint8_t)record->status);
        fields[field_count].field_index = 5U;
        fields[field_count].bytes = status_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_device_id) {
        fields[field_count].field_index = 6U;
        fields[field_count].bytes = (const uint8_t*)record->device_id;
        fields[field_count].length = record->device_id_length;
        field_count += 1U;
    }
    if (record->has_raw_payload) {
        fields[field_count].field_index = 7U;
        fields[field_count].bytes = record->raw_payload;
        fields[field_count].length = record->raw_payload_length;
        field_count += 1U;
    }
    if (record->has_readings) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, readings_bytes, sizeof(readings_bytes));
        (void)quarry_c_write_varuint(&writer, record->readings_count);
        for (uint32_t element_index = 0U; element_index < record->readings_count && element_index < 4U; ++element_index) {
            (void)quarry_c_write_i16(&writer, record->readings[element_index]);
        }
        fields[field_count].field_index = 8U;
        fields[field_count].bytes = readings_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    size_t size = 0U;
    (void)quarry_c_record_encoded_size(fields, field_count, &size);
    return size;
}

hil_telemetry_SensorSample_encode_result_t hil_telemetry_SensorSample_encode(const hil_telemetry_SensorSample_t* record, uint8_t* output, size_t output_capacity) {
    hil_telemetry_SensorSample_encode_result_t result;
    result.status = QUARRY_C_STATUS_OK;
    result.bytes_written = 0U;
    quarry_c_field_t fields[9];
    size_t field_count = 0U;
    uint8_t sequence_bytes[4];
    uint8_t timestamp_ms_bytes[8];
    uint8_t temperature_c_bytes[4];
    uint8_t battery_mv_bytes[2];
    uint8_t calibrated_bytes[1];
    uint8_t status_bytes[1];
    uint8_t readings_bytes[13];
    if (record->has_sequence) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, sequence_bytes, sizeof(sequence_bytes));
        const quarry_c_status_t field_status = quarry_c_write_u32(&writer, record->sequence);
        if (field_status != QUARRY_C_STATUS_OK) {
            result.status = field_status;
            return result;
        }
        fields[field_count].field_index = 0U;
        fields[field_count].bytes = sequence_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_timestamp_ms) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, timestamp_ms_bytes, sizeof(timestamp_ms_bytes));
        const quarry_c_status_t field_status = quarry_c_write_u64(&writer, record->timestamp_ms);
        if (field_status != QUARRY_C_STATUS_OK) {
            result.status = field_status;
            return result;
        }
        fields[field_count].field_index = 1U;
        fields[field_count].bytes = timestamp_ms_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_temperature_c) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, temperature_c_bytes, sizeof(temperature_c_bytes));
        const quarry_c_status_t field_status = quarry_c_write_f32(&writer, record->temperature_c);
        if (field_status != QUARRY_C_STATUS_OK) {
            result.status = field_status;
            return result;
        }
        fields[field_count].field_index = 2U;
        fields[field_count].bytes = temperature_c_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_battery_mv) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, battery_mv_bytes, sizeof(battery_mv_bytes));
        const quarry_c_status_t field_status = quarry_c_write_u16(&writer, record->battery_mv);
        if (field_status != QUARRY_C_STATUS_OK) {
            result.status = field_status;
            return result;
        }
        fields[field_count].field_index = 3U;
        fields[field_count].bytes = battery_mv_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_calibrated) {
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, calibrated_bytes, sizeof(calibrated_bytes));
        const quarry_c_status_t field_status = quarry_c_write_bool(&writer, record->calibrated);
        if (field_status != QUARRY_C_STATUS_OK) {
            result.status = field_status;
            return result;
        }
        fields[field_count].field_index = 4U;
        fields[field_count].bytes = calibrated_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_status) {
        if (!(record->status == 0 || record->status == 1 || record->status == 2)) {
            result.status = QUARRY_C_STATUS_UNKNOWN_ENUM_VALUE;
            return result;
        }
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, status_bytes, sizeof(status_bytes));
        const quarry_c_status_t field_status = quarry_c_write_u8(&writer, (uint8_t)record->status);
        if (field_status != QUARRY_C_STATUS_OK) {
            result.status = field_status;
            return result;
        }
        fields[field_count].field_index = 5U;
        fields[field_count].bytes = status_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    if (record->has_device_id) {
        if (record->device_id_length > 16U) {
            result.status = QUARRY_C_STATUS_BOUNDS_EXCEEDED;
            return result;
        }
        if (!quarry_c_is_valid_utf8((const uint8_t*)record->device_id, record->device_id_length)) {
            result.status = QUARRY_C_STATUS_INVALID_UTF8;
            return result;
        }
        fields[field_count].field_index = 6U;
        fields[field_count].bytes = (const uint8_t*)record->device_id;
        fields[field_count].length = record->device_id_length;
        field_count += 1U;
    }
    if (record->has_raw_payload) {
        if (record->raw_payload_length > 8U) {
            result.status = QUARRY_C_STATUS_BOUNDS_EXCEEDED;
            return result;
        }
        fields[field_count].field_index = 7U;
        fields[field_count].bytes = record->raw_payload;
        fields[field_count].length = record->raw_payload_length;
        field_count += 1U;
    }
    if (record->has_readings) {
        if (record->readings_count > 4U) {
            result.status = QUARRY_C_STATUS_BOUNDS_EXCEEDED;
            return result;
        }
        quarry_c_writer_t writer;
        quarry_c_writer_init(&writer, readings_bytes, sizeof(readings_bytes));
        const quarry_c_status_t count_status = quarry_c_write_varuint(&writer, record->readings_count);
        if (count_status != QUARRY_C_STATUS_OK) {
            result.status = count_status;
            return result;
        }
        for (uint32_t element_index = 0U; element_index < record->readings_count && element_index < 4U; ++element_index) {
            const quarry_c_status_t element_status = quarry_c_write_i16(&writer, record->readings[element_index]);
            if (element_status != QUARRY_C_STATUS_OK) {
                result.status = element_status;
                return result;
            }
        }
        fields[field_count].field_index = 8U;
        fields[field_count].bytes = readings_bytes;
        fields[field_count].length = writer.length;
        field_count += 1U;
    }
    result.status = quarry_c_encode_record(1U, fields, field_count, output, output_capacity, &result.bytes_written);
    return result;
}

hil_telemetry_SensorSample_decode_result_t hil_telemetry_SensorSample_decode(const uint8_t* input, size_t input_length) {
    hil_telemetry_SensorSample_decode_result_t result;
    result.status = QUARRY_C_STATUS_OK;
    result.has_byte_offset = false;
    result.byte_offset = 0U;
    memset(&result.value, 0, sizeof(result.value));

    quarry_c_parsed_record_t parsed;
    size_t error_offset = 0U;
    const quarry_c_status_t parse_status =
        quarry_c_parse_record(input, input_length, &parsed, &error_offset);
    if (parse_status != QUARRY_C_STATUS_OK) {
        result.status = parse_status;
        if (parse_status != QUARRY_C_STATUS_UNSUPPORTED_FIELD_COUNT) {
            result.has_byte_offset = true;
            result.byte_offset = error_offset;
        }
        return result;
    }
    if (parsed.record_id != 1U) {
        result.status = QUARRY_C_STATUS_UNEXPECTED_RECORD_ID;
        result.has_byte_offset = true;
        result.byte_offset = 0U;
        return result;
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 0U, &field_view, &field_found);
        if (field_found) {
            if (field_view.length != 4U) {
                result.status = QUARRY_C_STATUS_INVALID_FIELD_LENGTH;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            quarry_c_reader_t field_reader;
            quarry_c_reader_init(&field_reader, field_view.bytes, field_view.length);
            const quarry_c_status_t field_status = quarry_c_read_u32(&field_reader, &result.value.sequence);
            if (field_status != QUARRY_C_STATUS_OK) {
                result.status = field_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            result.value.has_sequence = true;
        }
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 1U, &field_view, &field_found);
        if (field_found) {
            if (field_view.length != 8U) {
                result.status = QUARRY_C_STATUS_INVALID_FIELD_LENGTH;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            quarry_c_reader_t field_reader;
            quarry_c_reader_init(&field_reader, field_view.bytes, field_view.length);
            const quarry_c_status_t field_status = quarry_c_read_u64(&field_reader, &result.value.timestamp_ms);
            if (field_status != QUARRY_C_STATUS_OK) {
                result.status = field_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            result.value.has_timestamp_ms = true;
        }
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 2U, &field_view, &field_found);
        if (field_found) {
            if (field_view.length != 4U) {
                result.status = QUARRY_C_STATUS_INVALID_FIELD_LENGTH;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            quarry_c_reader_t field_reader;
            quarry_c_reader_init(&field_reader, field_view.bytes, field_view.length);
            const quarry_c_status_t field_status = quarry_c_read_f32(&field_reader, &result.value.temperature_c);
            if (field_status != QUARRY_C_STATUS_OK) {
                result.status = field_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            result.value.has_temperature_c = true;
        }
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 3U, &field_view, &field_found);
        if (field_found) {
            if (field_view.length != 2U) {
                result.status = QUARRY_C_STATUS_INVALID_FIELD_LENGTH;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            quarry_c_reader_t field_reader;
            quarry_c_reader_init(&field_reader, field_view.bytes, field_view.length);
            const quarry_c_status_t field_status = quarry_c_read_u16(&field_reader, &result.value.battery_mv);
            if (field_status != QUARRY_C_STATUS_OK) {
                result.status = field_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            result.value.has_battery_mv = true;
        }
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 4U, &field_view, &field_found);
        if (field_found) {
            if (field_view.length != 1U) {
                result.status = QUARRY_C_STATUS_INVALID_FIELD_LENGTH;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            quarry_c_reader_t field_reader;
            quarry_c_reader_init(&field_reader, field_view.bytes, field_view.length);
            const quarry_c_status_t field_status = quarry_c_read_bool(&field_reader, &result.value.calibrated);
            if (field_status != QUARRY_C_STATUS_OK) {
                result.status = field_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            result.value.has_calibrated = true;
        }
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 5U, &field_view, &field_found);
        if (field_found) {
            if (field_view.length != 1U) {
                result.status = QUARRY_C_STATUS_INVALID_FIELD_LENGTH;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            quarry_c_reader_t field_reader;
            quarry_c_reader_init(&field_reader, field_view.bytes, field_view.length);
            uint8_t status_raw = 0;
            const quarry_c_status_t field_status = quarry_c_read_u8(&field_reader, &status_raw);
            if (field_status != QUARRY_C_STATUS_OK) {
                result.status = field_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            if (!(status_raw == 0 || status_raw == 1 || status_raw == 2)) {
                result.status = QUARRY_C_STATUS_UNKNOWN_ENUM_VALUE;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            result.value.status = (hil_telemetry_Status_t)status_raw;
            result.value.has_status = true;
        }
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 6U, &field_view, &field_found);
        if (field_found) {
            const quarry_c_status_t field_status = quarry_c_copy_bounded(
                (uint8_t*)result.value.device_id, 16U, field_view.bytes, field_view.length);
            if (field_status != QUARRY_C_STATUS_OK) {
                result.status = field_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            if (!quarry_c_is_valid_utf8(field_view.bytes, field_view.length)) {
                result.status = QUARRY_C_STATUS_INVALID_UTF8;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            result.value.device_id[field_view.length] = '\0';
            result.value.device_id_length = (uint32_t)field_view.length;
            result.value.has_device_id = true;
        }
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 7U, &field_view, &field_found);
        if (field_found) {
            const quarry_c_status_t field_status = quarry_c_copy_bounded(
                result.value.raw_payload, 8U, field_view.bytes, field_view.length);
            if (field_status != QUARRY_C_STATUS_OK) {
                result.status = field_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            result.value.raw_payload_length = (uint32_t)field_view.length;
            result.value.has_raw_payload = true;
        }
    }

    {
        quarry_c_field_view_t field_view;
        bool field_found = false;
        (void)quarry_c_find_field(&parsed, 8U, &field_view, &field_found);
        if (field_found) {
            quarry_c_reader_t array_reader;
            quarry_c_reader_init(&array_reader, field_view.bytes, field_view.length);
            uint64_t element_count_raw = 0;
            const quarry_c_status_t count_status = quarry_c_read_varuint(&array_reader, &element_count_raw);
            if (count_status != QUARRY_C_STATUS_OK) {
                result.status = count_status;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            if (element_count_raw > 4U) {
                result.status = QUARRY_C_STATUS_BOUNDS_EXCEEDED;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset;
                return result;
            }
            const uint32_t element_count = (uint32_t)element_count_raw;
            const size_t element_width = 2U;
            const size_t remaining_bytes = field_view.length - array_reader.offset;
            if (element_width == 0U || element_count > remaining_bytes / element_width || remaining_bytes != (size_t)element_count * element_width) {
                result.status = QUARRY_C_STATUS_INVALID_FIELD_LENGTH;
                result.has_byte_offset = true;
                result.byte_offset = field_view.byte_offset + array_reader.offset;
                return result;
            }
            for (uint32_t element_index = 0U; element_index < element_count; ++element_index) {
                const quarry_c_status_t element_status = quarry_c_read_i16(&array_reader, &result.value.readings[element_index]);
                if (element_status != QUARRY_C_STATUS_OK) {
                    result.status = element_status;
                    result.has_byte_offset = true;
                    result.byte_offset = field_view.byte_offset + array_reader.offset;
                    return result;
                }
            }
            result.value.readings_count = element_count;
            result.value.has_readings = true;
        }
    }

    return result;
}
