/* Generated by Quarry (C backend). */
#ifndef QUARRY_GENERATED_C_HIL_TELEMETRY_GENERATED_H_
#define QUARRY_GENERATED_C_HIL_TELEMETRY_GENERATED_H_

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <quarry/runtime_c/binary_record.h>

#if QUARRY_C_GENERATED_CODE_API_VERSION != 2U
#error "Generated Quarry C code is incompatible with the installed Quarry C runtime. Regenerate the code using a compatible quarry-schema-compiler release."
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    HIL_TELEMETRY_STATUS_OK = 0,
    HIL_TELEMETRY_STATUS_WARNING = 1,
    HIL_TELEMETRY_STATUS_FAULT = 2,
} hil_telemetry_Status_t;

typedef struct {
    bool has_sequence;
    uint32_t sequence;
    bool has_timestamp_ms;
    uint64_t timestamp_ms;
    bool has_temperature_c;
    float temperature_c;
    bool has_battery_mv;
    uint16_t battery_mv;
    bool has_calibrated;
    bool calibrated;
    bool has_status;
    hil_telemetry_Status_t status;
    bool has_device_id;
    char device_id[17];
    uint32_t device_id_length;
    bool has_raw_payload;
    uint8_t raw_payload[8];
    uint32_t raw_payload_length;
    bool has_readings;
    int16_t readings[4];
    uint32_t readings_count;
} hil_telemetry_SensorSample_t;

void hil_telemetry_SensorSample_init(hil_telemetry_SensorSample_t* record);

size_t hil_telemetry_SensorSample_encoded_size(const hil_telemetry_SensorSample_t* record);

typedef struct {
    quarry_c_status_t status;
    size_t bytes_written;
} hil_telemetry_SensorSample_encode_result_t;

hil_telemetry_SensorSample_encode_result_t hil_telemetry_SensorSample_encode(const hil_telemetry_SensorSample_t* record, uint8_t* output, size_t output_capacity);

typedef struct {
    quarry_c_status_t status;
    hil_telemetry_SensorSample_t value;
    bool has_byte_offset;
    size_t byte_offset;
} hil_telemetry_SensorSample_decode_result_t;

hil_telemetry_SensorSample_decode_result_t hil_telemetry_SensorSample_decode(const uint8_t* input, size_t input_length);

#ifdef __cplusplus
}
#endif

#endif /* QUARRY_GENERATED_C_HIL_TELEMETRY_GENERATED_H_ */
